permalink: /:year/:month/:title.html
auto: true
server: true
pygments: true
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

title: The corrosion of Aaron Stone
url: http://sodabrew.github.com/

author:
  name: Aaron Stone
  email: aaron@serendipity.cx
  github: sodabrew
  twitter: sodabrew
  facebook: sodabrew
  pinterest: sodabrew
  yelp: sodabrew

ads:
  google:
    client: "ca-pub-1834313190562288"
    slot: "8867724119"
    width: 180
    height: 150

analytics:
  provider: google
  google:
    tracking_id: "UA-11411607-1"
