permalink: /:year/:month/:title.html
auto: true
server: true
pygments: true
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

title: The corrosion of Aaron Stone
url: http://sodabrew.github.com/

author:
  name: Aaron Stone
  email: aaron@serendipity.cx
  github: sodabrew
  twitter: sodabrew
  facebook: sodabrew
  yelp: sodabrew
