permalink: /:year/:month/:title.html
exclude: ["README.md", "Rakefile", "changelog.md", "Gemfile", "Gemfile.lock", "vendor"]

title: The corrosion of Aaron Stone
production_url: http://sodabrew.com

author:
  name: Aaron Stone
  email: aaron@serendipity.cx
  github: sodabrew
  twitter: sodabrew
  facebook: sodabrew
  pinterest: sodabrew
  yelp: sodabrew

font_awesome:
  js: 'https://use.fontawesome.com/e28a43ff56.js'

ads:
  google:
    client: "ca-pub-1834313190562288"
    slot: "8867724119"
    width: 180
    height: 150

JB:
  analytics:
    provider: google
    google:
      tracking_id: "UA-11411607-1"

  comments:
    provider: facebook
    facebook:
      appid: sodabrew
      num_posts: 5
      width: 580
      colorscheme: light
